# Generated by Django 4.2.16 on 2024-12-02 13:54

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0028_alter_therapist_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='officepicture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='invoice_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('en', 'anglais'), ('fr', 'français'), ('de', 'allemand'), ('ru', 'russe'), ('it', 'italien'), ('es', 'espagnol'), ('nl', 'néerlandais'), ('pl', 'polonais'), ('pt', 'portugais'), ('ro', 'roumain'), ('hu', 'hongrois')], max_length=2), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='membership',
            field=models.CharField(choices=[('pending', 'En attente / suspendu'), ('invitee', 'Invité'), ('member', 'Membre'), ('premium', 'Payant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='therapistpatient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
