# Generated by Django 5.1.4 on 2024-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0029_alter_office_id_alter_officepicture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='invoice_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
