# Generated by Django 5.1.4 on 2025-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0029_alter_therapist_languages_alter_therapist_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='URL Calendly du thérapeute', max_length=255, null=True),
        ),
    ]
